name: bible
description: A bible app, built in Flutter.

dependencies:
  flutter:
    sdk: flutter

  archive: any
  barcode_scan: any
  dio: any
  cloud_firestore: any
  firebase_analytics: any
  firebase_auth: any
  firebase_core: any
  firebase_database: any
  firebase_messaging: any
  firebase_remote_config: any
  firebase_storage: any
  flutter_facebook_login: any
  flutter_search_bar: any
  google_sign_in: any
  html: any
  html_unescape: any
  html2md: any
  http: any
  intl: any
  path_provider: any
  qr_flutter: any
  share: any
  shared_preferences: any
  simple_permissions: any
  sortedmap: any
  flutter_swiper: any
  sqflite: any
  tuple: any
  url_launcher: any
  uuid: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
     - assets/files/about.txt
     - assets/images/g-logo.png
     - assets/images/f-logo-c.png
     - assets/images/f-logo-w.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
          weight: 600
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
          weight: 600
    - family: Rosemary
      fonts:
        - asset: assets/fonts/Rosemary-Regular.ttf
          weight: 600
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf
          weight: 600